//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo.MVC5.TodoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TodoService.IToDoService")]
    public interface IToDoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/GetToDoItems", ReplyAction="http://tempuri.org/IToDoService/GetToDoItemsResponse")]
        ToDo.WCF.Contract.ToDoItemContract[] GetToDoItems(string idFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/GetToDoItems", ReplyAction="http://tempuri.org/IToDoService/GetToDoItemsResponse")]
        System.Threading.Tasks.Task<ToDo.WCF.Contract.ToDoItemContract[]> GetToDoItemsAsync(string idFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/SaveToDoItem", ReplyAction="http://tempuri.org/IToDoService/SaveToDoItemResponse")]
        string SaveToDoItem(ToDo.WCF.Contract.ToDoItemContract toDoItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/SaveToDoItem", ReplyAction="http://tempuri.org/IToDoService/SaveToDoItemResponse")]
        System.Threading.Tasks.Task<string> SaveToDoItemAsync(ToDo.WCF.Contract.ToDoItemContract toDoItem);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IToDoServiceChannel : ToDo.MVC5.TodoService.IToDoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ToDoServiceClient : System.ServiceModel.ClientBase<ToDo.MVC5.TodoService.IToDoService>, ToDo.MVC5.TodoService.IToDoService {
        
        public ToDoServiceClient() {
        }
        
        public ToDoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ToDoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToDoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToDoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ToDo.WCF.Contract.ToDoItemContract[] GetToDoItems(string idFilter) {
            return base.Channel.GetToDoItems(idFilter);
        }
        
        public System.Threading.Tasks.Task<ToDo.WCF.Contract.ToDoItemContract[]> GetToDoItemsAsync(string idFilter) {
            return base.Channel.GetToDoItemsAsync(idFilter);
        }
        
        public string SaveToDoItem(ToDo.WCF.Contract.ToDoItemContract toDoItem) {
            return base.Channel.SaveToDoItem(toDoItem);
        }
        
        public System.Threading.Tasks.Task<string> SaveToDoItemAsync(ToDo.WCF.Contract.ToDoItemContract toDoItem) {
            return base.Channel.SaveToDoItemAsync(toDoItem);
        }
    }
}
